[tools]
aube = "v1.18.0"
node = "26.3.0"
"npm:sfw" = "latest"
"aqua:zizmorcore/zizmor" = "1.25.2"
"aqua:rhysd/actionlint" = "1.7.12"
"aqua:koalaman/shellcheck" = "0.11.0"

#[hooks]
#postinstall = "pn install"

[settings]
experimental = true
paranoid = true
